let controllers = require('./../controllers')
let middlewares = require('./../middlewares')
let routes = require('./../routes')

module.exports = (app) => {
  app.get('/', middlewares.auth.isAuthenticated, controllers.home.index)
  app.get('/users/login', controllers.users.login)
  app.post('/users/authenticate', controllers.users.authenticate)
  app.post('/users/logout', controllers.users.logout)

  app.get('/archive', middlewares.auth.isInRole('user'), controllers.orders.archiveView)
  app.get('/customers', middlewares.auth.isInRole('user'), controllers.customers.index)
  app.get('/customer/?:id', middlewares.auth.isInRole('user'), controllers.customers.details)
  app.get('/translators', middlewares.auth.isInRole('user'), controllers.translators.index)
  app.get('/languages', middlewares.auth.isInRole('admin'), controllers.languages.index)
  app.get('/orders', middlewares.auth.isInRole('user'), controllers.orders.index)
  app.get('/order/:id', middlewares.auth.isInRole('user'), controllers.orders.details)
  app.get('/orders/pdf/:id', middlewares.auth.isInRole('admin'), controllers.orders.pdf)
  app.get('/users', middlewares.auth.isInRole('admin'), controllers.users.index)
  app.get('/insights', middlewares.auth.isInRole('admin'), controllers.insights.index)
  app.get('/doc-types', middlewares.auth.isInRole('user'), controllers.docTypes.index)
  app.get('/not-paid-orders/pdf', middlewares.auth.isInRole('user'), controllers.orders.notPaidOrdersPdf)
  app.get('/not-paid-orders', middlewares.auth.isInRole('user'), controllers.orders.notPaid)
  app.get('/not-paid-orders/:id', middlewares.auth.isInRole('user'), controllers.orders.notPaidByCustomerView)
  app.get('/not-paid-honorary', middlewares.auth.isInRole('user'), controllers.translators.notPaidHonoraryView)
  app.get('/not-paid-honorary/:id', middlewares.auth.isInRole('user'), controllers.translators.notPaidHonoraryByTranslatorView)
  app.get('/not-paid-honorary/pdf/:translatorId', middlewares.auth.isInRole('admin'), controllers.orders.notPaidHonoraryByTranslatorPdf)
  app.get('/ministries', middlewares.auth.isInRole('admin'), controllers.ministries.index)
  app.get('/documents', middlewares.auth.isInRole('user'), controllers.documents.index)

  app.use('/api/customers', routes.customers)
  app.use('/api/translators', routes.translators)
  app.use('/api/languages', routes.languages)
  app.use('/api/orders', routes.orders)
  app.use('/api/users', routes.users)
  app.use('/api/doc-types', routes.docTypes)
  app.use('/api/order-items', routes.orderItems)
  app.use('/api/ministries', routes.ministries)
  app.use('/api/documents', routes.documents)

  app.all('*', controllers.home.notFound)
}
